"""30-day trial tracking and offline perpetual license verification.

License keys are issued by windows/licensing_tool/generate_license.py and
verified here against an embedded Ed25519 public key - no license server
is required. The trial start date is recorded in the Windows registry
(HKCU\\Software\\StarTerm) so it survives deletion of %APPDATA%; on
non-Windows platforms (used for development/testing) it falls back to a
JSON file in the app data directory.
"""

import base64
import datetime
import json
import struct
import sys

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

from .config import get_app_data_dir, load_settings, save_settings

PRODUCT = "star_term"
TRIAL_DAYS = 30

# Public half of the keypair generated by licensing_tool/generate_keypair.py.
PUBLIC_KEY_HEX = "4d055cd85dfd9c1849759c3c596b65ad99b1aee31103c6c43ea5bc98537697e6"
_PUBLIC_KEY = Ed25519PublicKey.from_public_bytes(bytes.fromhex(PUBLIC_KEY_HEX))

TRIAL_MARKER_FILE = "trial_marker.json"
REGISTRY_KEY_PATH = r"Software\StarTerm"


def parse_license_key(key_str: str) -> dict | None:
    """Verifies a license key string, returning the license payload dict
    (licensee, email, issued, product) if valid, or None if it's malformed,
    tampered, or for a different product."""
    cleaned = "".join(key_str.split())
    try:
        token = base64.urlsafe_b64decode(cleaned)
        (payload_len,) = struct.unpack_from(">H", token, 0)
        payload_bytes = token[2:2 + payload_len]
        signature = token[2 + payload_len:]
        _PUBLIC_KEY.verify(signature, payload_bytes)
        payload = json.loads(payload_bytes)
    except (ValueError, InvalidSignature, struct.error):
        return None

    if payload.get("product") != PRODUCT:
        return None
    return payload


def get_license_info() -> dict | None:
    """Returns the verified info for the currently stored license key, or
    None if no key is stored or it's invalid."""
    key_str = load_settings().get("license_key")
    if not key_str:
        return None
    return parse_license_key(key_str)


def save_license_key(key_str: str) -> dict | None:
    """Verifies and stores a license key. Returns the parsed license info
    on success, or None (and leaves settings unchanged) if invalid."""
    info = parse_license_key(key_str)
    if info is None:
        return None
    settings = load_settings()
    settings["license_key"] = key_str.strip()
    save_settings(settings)
    return info


def clear_license_key():
    settings = load_settings()
    if settings.pop("license_key", None) is not None:
        save_settings(settings)


# ----------------------------------------------------------------------
# Trial marker storage
# ----------------------------------------------------------------------

def _read_trial_marker() -> dict:
    if sys.platform == "win32":
        import winreg

        def query(key, name):
            try:
                value, _type = winreg.QueryValueEx(key, name)
                return value
            except FileNotFoundError:
                return None

        try:
            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH) as key:
                return {
                    "trial_start": query(key, "TrialStart"),
                    "last_seen": query(key, "LastSeen"),
                }
        except FileNotFoundError:
            return {}

    path = get_app_data_dir() / TRIAL_MARKER_FILE
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _write_trial_marker(marker: dict):
    if sys.platform == "win32":
        import winreg

        with winreg.CreateKey(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH) as key:
            if marker.get("trial_start"):
                winreg.SetValueEx(key, "TrialStart", 0, winreg.REG_SZ, marker["trial_start"])
            if marker.get("last_seen"):
                winreg.SetValueEx(key, "LastSeen", 0, winreg.REG_SZ, marker["last_seen"])
        return

    path = get_app_data_dir() / TRIAL_MARKER_FILE
    with open(path, "w", encoding="utf-8") as f:
        json.dump(marker, f, indent=2)


def get_trial_status() -> dict:
    """Returns {"days_remaining": int, "expired": bool}, recording the
    trial start date on first call. Guards against trivial trial resets
    via clock rollback: if the system clock appears to have moved
    backwards since the last run, the trial is treated as expired."""
    today = datetime.date.today()
    marker = _read_trial_marker()

    trial_start_str = marker.get("trial_start")
    last_seen_str = marker.get("last_seen")

    if trial_start_str:
        trial_start = datetime.date.fromisoformat(trial_start_str)
    else:
        trial_start = today

    last_seen = datetime.date.fromisoformat(last_seen_str) if last_seen_str else today
    clock_rolled_back = today < last_seen

    days_elapsed = (today - trial_start).days
    days_remaining = max(0, TRIAL_DAYS - days_elapsed)
    expired = clock_rolled_back or days_remaining <= 0

    _write_trial_marker({
        "trial_start": trial_start.isoformat(),
        "last_seen": max(today, last_seen).isoformat(),
    })

    return {"days_remaining": 0 if clock_rolled_back else days_remaining, "expired": expired}


def get_license_status() -> dict:
    license_info = get_license_info()
    trial = get_trial_status()
    return {
        "licensed": license_info is not None,
        "license_info": license_info,
        "trial_days_remaining": trial["days_remaining"],
        "trial_expired": trial["expired"],
    }
